services:
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: admin1234
    container_name: myshow-postgres_db
    ports:
      - 5432:5432
    volumes:
      - myshow_db_data:/var/lib/postgresql/data

volumes:
  myshow_db_data:
